apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: web
  namespace: bakseter-no
spec:
  endpointSelector: {}

  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: envoy-gateway-system
            gateway.envoyproxy.io/owning-gateway-name: cloudflared-gateway
      toPorts:
        - rules:
            http:
              - path: /
                method: GET
              - path: /favicon.ico
                method: GET
          ports:
            - port: '8080'
              protocol: TCP

  egress: []
