apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: bakseter-no
  namespace: bakseter-no
spec:
  endpointSelector: {}

  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: envoy-gateway-system
            gateway.envoyproxy.io/owning-gateway-name: cloudflared-gateway
      toPorts:
        - rules:
            http:
              - path: /
                method: GET
              - path: /favicon.ico
                method: GET
              - path: /status
                method: GET
          ports:
            - port: '8080'
              protocol: TCP

  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
            app.kubernetes.io/name: alloy
      toPorts:
        - ports:
            - port: '4317'
              protocol: TCP
