apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web
  namespace: bakseter-net
spec:
  parentRefs:
    - name: cloudflared-gateway
      namespace: cloudflared
      group: gateway.networking.k8s.io # for argocd diff
      kind: Gateway

  hostnames:
    - bakseter.net

  rules:
    - matches:
        - path:
            type: Exact
            value: /
        - path:
            type: Exact
            value: /favicon.ico

      backendRefs:
        - name: web
          port: 80
          group: '' # for argocd diff
          kind: Service # for argocd diff
          weight: 1 # for argocd diff
